name: Update Exchange Rate Every 12 hours

# This workflow runs every minute
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 Hours (due to GitHub's limitations)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_rate:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the Python script
    - name: Run the update script
      env:
        EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
      run: |
        python main.py
